[workspace]
resolver = "3"

members = [
    "crates/media",
    "crates/server",
]

default-members = [
    "crates/server",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.53.1", features = ["full"] }
axum = "0.8.9"
futures-util = "0.3.34"
uuid = { version = "1.24.1", features = ["v7"] }
# serde = { version = "1.0.229" }
# serde_json = { version = "1.71.0" }

media = { path = "crates/media" }
